### ISSUE TITLE
LunchSet failed (ArgumentError)

### ISSUE THREAD

**Issue by JimMcKenzieSmith** [fredbenenson/lunch-roulette#2]
Hi Fred,

Will you help me understand why I am getting this error?  

Here is my staff data, which is example.csv below:
https://docs.google.com/spreadsheet/ccc?key=0AkcfyAeGuuGVdGhUS0tvSmJQN2VxeW1lSG80STd0MFE&usp=sharing

Here is the output:

```
jimsmith@it-sweng01:~/workspace/lunch-roulette$ ruby lib/lunch_roulette.rb -v data/example.csv 
Generating  sets...
Invalid Sets: 918
Valid Sets: 82
lib/lunch_roulette.rb:82:in `sort': comparison of LunchRoulette::LunchSet with LunchRoulette::LunchSet failed (ArgumentError)
    from lib/lunch_roulette.rb:82:in `spin!'
    from lib/lunch_roulette.rb:101:in `<main>'
```

**Comment by flex-tuan** [comment]
I think this is great! I got this result after downloading the repo and running it with the supplied csv:
```
$ ruby lib/lunch_roulette.rb -v data/staff.csv
Generating  sets...
Invalid Sets: 1000
Valid Sets: 0
No valid sets generated, sorry.
```
Any ideas what i'm doing wrong?
Thanks!

**Comment by jeffjeffjeffrey** [comment]
Hey @flex-tuan, glad you like it! Sometimes it's possible for the weights and thresholds in [mappings_and_weights.yml](https://github.com/fredbenenson/lunch-roulette/blob/master/config/mappings_and_weights.yml) to be too strict for your particular set of people to afford a valid lunch set. Could that be it?

**Comment by ghost** [comment]
Great idea, thanks for releasing it out to the community!
PS - I am also getting "No valid sets generated, sorry."
What are some of the factors that could be changed to avoir this message? I've tried to change our staff file with it's respective teams and specialties as close as possible to the one provided. My file has about 500 people in it. Any suggestions as per how many specialties and titles are required to make it work with that amount of ppl? 
Update: I've tweaked the logic for specialties as the ratios were not quite the same as those in the original sample.
